# update_assets.ps1 - Scans all photos and videos and generates photos_data.js

$cutePics = @(Get-ChildItem -Path "anushka cute pics" -Include *.jpeg,*.jpg,*.png,*.webp -Recurse -File | ForEach-Object { "anushka cute pics/" + $_.Name })
$funnyPics = @(Get-ChildItem -Path "anushka funny pics" -Include *.jpeg,*.jpg,*.png,*.webp -Recurse -File | ForEach-Object { "anushka funny pics/" + $_.Name })

$cuteVideos = @(Get-ChildItem -Path "anushka video" -Include *.mp4,*.mov,*.webm -Recurse -File -ErrorAction SilentlyContinue | ForEach-Object { "anushka video/" + $_.Name })
$funnyVideos = @(Get-ChildItem -Path "anushka funny pics" -Include *.mp4,*.mov,*.webm -Recurse -File -ErrorAction SilentlyContinue | ForEach-Object { "anushka funny pics/" + $_.Name })

function To-JsonArray($arr) {
    if ($null -eq $arr -or $arr.Count -eq 0) {
        return "[]"
    }
    $json = $arr | ConvertTo-Json -Compress
    if ($arr.Count -eq 1) {
        return "[$json]"
    }
    return $json
}

$content = @"
// Auto-generated by update_assets.ps1
window.CUTE_PICS = $(To-JsonArray $cutePics);
window.FUNNY_PICS = $(To-JsonArray $funnyPics);
window.CUTE_VIDEOS = $(To-JsonArray $cuteVideos);
window.FUNNY_VIDEOS = $(To-JsonArray $funnyVideos);
"@

Set-Content -Path "photos_data.js" -Value $content -Encoding UTF8
Write-Host "Updated photos_data.js successfully!"
Write-Host "Cute pics: $($cutePics.Count)"
Write-Host "Funny pics: $($funnyPics.Count)"
Write-Host "Cute videos: $($cuteVideos.Count)"
Write-Host "Funny videos: $($funnyVideos.Count)"
