# update_assets.ps1 - Scans all photos and videos natively inside 'anushka ka surprise' and generates photos_data.js

function To-JsonArray($arr) {
    if (-not $arr -or $arr.Count -eq 0) {
        return "[]"
    }
    $items = @($arr | ForEach-Object { ConvertTo-Json $_ -Compress })
    return "[" + ($items -join ",") + "]"
}

$cutePics = @(Get-ChildItem -Path "anushka cute pics" -Include *.jpeg,*.jpg,*.png,*.webp -Recurse -File -ErrorAction SilentlyContinue | ForEach-Object { "anushka cute pics/" + $_.Name })
$funnyPics = @(Get-ChildItem -Path "anushka funny pics" -Include *.jpeg,*.jpg,*.png,*.webp -Recurse -File -ErrorAction SilentlyContinue | ForEach-Object { "anushka funny pics/" + $_.Name })

$funnyVideos = @(Get-ChildItem -Path "anushka funny pics" -Include *.mp4,*.mov,*.webm -Recurse -File -ErrorAction SilentlyContinue | ForEach-Object { "anushka funny pics/" + $_.Name })

$cutePicsJson = To-JsonArray $cutePics
$funnyPicsJson = To-JsonArray $funnyPics
$cuteVideosJson = "[]"
$funnyVideosJson = To-JsonArray $funnyVideos

$content = @"
// Auto-generated by update_assets.ps1
window.CUTE_PICS = $cutePicsJson;
window.FUNNY_PICS = $funnyPicsJson;
window.CUTE_VIDEOS = $cuteVideosJson;
window.FUNNY_VIDEOS = $funnyVideosJson;
"@

Set-Content -Path "photos_data.js" -Value $content -Encoding UTF8
Write-Host "Updated photos_data.js successfully!"
Write-Host "Cute pics: $($cutePics.Count)"
Write-Host "Funny pics: $($funnyPics.Count)"
Write-Host "Videos: $($funnyVideos.Count)"
